import { BookOpen, Download, GraduationCap, Star } from 'lucide-react';

import { Course } from './types';

export const class9Courses: Course[] = [
  {
    id: 1,
    category: 'New Syllabus',
    title: '9 Physics Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/physics.jpg',
    duration: '15 March 2026',
    rating: 4.5,
    downloads: '7K',
    slug: '9th-class-physics',
  },
  {
    id: 2,
    category: 'New Syllabus',
    title: '9 Turjuma-Tul-Quran Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/Quran.jpg',
    duration: '15 March 2026',
    rating: 4.2,
    downloads: '3K',
    slug: '9th-class-turjuma-tul-quran',
  },
  {
    id: 3,
    category: 'New Syllabus',
    title: '9 Islamiat Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/islamiat.jpg',
    duration: '15 March 2026',
    rating: 4.7,
    downloads: '6K',
    slug: '9th-class-islamiat',
  },
  {
    id: 4,
    category: 'New Syllabus',
    title: '9 Mathematics Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/MATH.jpg',
    duration: '15 March 2026',
    rating: 4.8,
    downloads: '12K',
    slug: '9th-class-mathematics',
  },
  {
    id: 5,
    category: 'New Syllabus',
    title: '9 Urdu Qawaid-e-Insha T.Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/INSHA.jpg',
    duration: '15 March 2026',
    rating: 4.4,
    downloads: '3K',
    slug: '9th-class-urdu-qawaid-e-insha',
  },
  {
    id: 6,
    category: 'New Syllabus',
    title: '9 Biology Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/BIOLOGY.jpg',
    duration: '15 March 2026',
    rating: 4.9,
    downloads: '15K',
    slug: '9th-class-biology',
  },
  {
    id: 7,
    category: 'New Syllabus',
    title: '9 Computer Science Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/COMPUTER.jpg',
    duration: '15 March 2026',
    rating: 4.8,
    downloads: '13K',
    slug: '9th-class-computer-science',
  },
  {
    id: 8,
    category: 'New Syllabus',
    title: '9 English Grammar Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/ENG GRAMER.jpg',
    duration: '15 March 2026',
    rating: 4.7,
    downloads: '5K',
    slug: '9th-class-english-grammar',
  },
  {
    id: 9,
    category: 'New Syllabus',
    title: '9 Urdu Text Book PDF',
    description: 'Click View & Download To Access Your Digital PCTB 9 Class Text Book Instantly',
    cover: '/models/textures/URDU.jpg',
    duration: '15 March 2026',
    rating: 4.9,
    downloads: '15K',
    slug: '9th-class-urdu',
  },
];

export const class9Subjects = [
  'Physics',
  'Maths',
  'Biology',
  'Chemistry',
  'Computer',
  'English',
  'Urdu',
  'Islamiat',
];

export const class9Stats = [
  { icon: BookOpen, value: '9+', label: 'Subjects' },
  { icon: Download, value: '80K+', label: 'Downloads' },
  { icon: Star, value: '4.7★', label: 'Avg Rating' },
  { icon: GraduationCap, value: 'Free', label: 'Always' },
];
